version: '3.8'
services:

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:5.7.22
        environment:
            MYSQL_DATABASE: admin
            MYSQL_USER: root #comment this one on first run
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - "33066:3306"
