# testing the API


### register an user
POST {{api}}register
X-Requested-With: XMLHttpRequest
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="first_name"
Content-Type: text/plain

Simone
--WebAppBoundary
Content-Disposition: form-data; name="last_name"
Content-Type: text/plain

Celia
--WebAppBoundary
Content-Disposition: form-data; name="email"
Content-Type: text/plain

simone.celia@simonecelia.it
--WebAppBoundary
Content-Disposition: form-data; name="password"
Content-Type: text/plain

pass
--WebAppBoundary
Content-Disposition: form-data; name="password_confirm"
Content-Type: text/plain

pass
--WebAppBoundary

### login
POST {{api}}login
X-Requested-With: XMLHttpRequest
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="email"
Content-Type: text/plain

admin@admin.com
--WebAppBoundary
Content-Disposition: form-data; name="password"
Content-Type: text/plain

password
--WebAppBoundary

### get authenticated user (with cookie from the login call)
GET {{api}}user
X-Requested-With: XMLHttpRequest
Cookie: Authorization=3|pKpl09u3Bk4PMOeigisvOs3frpuQyqAtW3Jg3CdT;

### logout
POST {{api}}logout
X-Requested-With: XMLHttpRequest
Cookie: Authorization=3|pKpl09u3Bk4PMOeigisvOs3frpuQyqAtW3Jg3CdT;

### get all users
GET {{api}}users?page=1

### create an user
POST {{api}}users
X-Requested-With: XMLHttpRequest
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="first_name"
Content-Type: text/plain

primo nome
--WebAppBoundary
Content-Disposition: form-data; name="last_name"
Content-Type: text/plain

cognome
--WebAppBoundary
Content-Disposition: form-data; name="email"
Content-Type: text/plain

email@provider.it
--WebAppBoundary

### get an user by id
GET {{api}}users/1

### update an user by id
PUT {{api}}users/6
Content-Type: application/x-www-form-urlencoded

first_name=mod&last_name=cognomeMod&email=email@mod.it

### delete an user by id
DELETE {{api}}users/6

### update current user info
PUT {{api}}users/info
Content-Type: application/x-www-form-urlencoded

first_name=simone_updated

### update current user password
PUT {{api}}users/password
Content-Type: application/x-www-form-urlencoded

password=pass&password_confirm=pass

###
